Repository vmware/powershell-module-for-vmware-cloud-foundation-password-management, pull requests merged in 2023-11, with the labels that each got.

#137 docs: add air-gapped install
  docs/install.md
  docs/snippets/copy-module-local-linux.sh
  docs/snippets/copy-module-local-windows.ps1
  docs/snippets/import-module-local-linux.ps1
  docs/snippets/pre-req-linux.sh
  docs/snippets/save-module-local-linux.ps1
  docs/snippets/save-module-local-windows.ps1
Labels: documentation

#138 chore: release preparation
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  docs/index.md
  docs/snippets/install-module.ps1
Labels: chore

#139 feat: add secure strings for sensitive parameters
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: enhancement

#143 chore: update copyright
  LICENSE
  Makefile
  NOTICE
  README.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
  docs/index.md
  mkdocs.yml
Labels: chore
