Repository vmware/powershell-module-for-vmware-cloud-foundation-password-management, pull requests merged in 2023-06, with the labels that each got.

#42 feat: enhance `Update-NsxtManagerPasswordComplexity` for VCF 5.0 and NSX 4.x
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: documentation, enhancement

#45 Fix: Fixed default values in `Get-PasswordPolicyDefault` cmdlet
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: documentation, needs-review

#49 feat: enhance `Update-NsxtManagerPasswordComplexity` and `Request-NsxtManagerPasswordComplexity` for `hash_algorithm`
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
  docs/documentation/functions/Update-NsxtManagerPasswordComplexity.md
Labels: enhancement

#51 feat: add support for isolated workload domain in `Publish-SSo*` and enhance `Get-PasswordPolicyDefault`
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: enhancement

#54 feat: enhanced `Get-PasswordPolicyDefault` cmdlet to overwrite existing JSON file using `force` parameter
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
  docs/documentation/functions/Get-PasswordPolicyDefault.md
Labels: documentation, needs-review

#56 feat: enhanced `Update-SsoPasswordComplexity` cmdlet to add validation on parameter values
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: documentation

#57 chore: release preparation
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/pull_request_template.md
  CHANGELOG.md
  LICENSE
  NOTICE
  VMware.CloudFoundation.PasswordManagement.psd1
  docs/community/index.md
  docs/index.md
  docs/snippets/install-module.ps1
  mkdocs.yml
Labels: documentation, chore

#62 fix: update connection tests
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: bug

#63 fix: module dependencies
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: enhancement, needs-review

#64 chore(gh): fix bug issue form
  .github/ISSUE_TEMPLATE/bug.yml
Labels: chore
