Repository vmware/powershell-module-for-vmware-cloud-foundation-password-management, pull requests merged in 2023-07, with the labels that each got.

#72 chore: update version
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
Labels: chore

#78 chore: update `RequiredModules`
  VMware.CloudFoundation.PasswordManagement.psd1
Labels: chore, dependencies

#76 fix: nsx-edge-pw-expiration
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: bug

#79 docs: update docs for wsa cmdlets
  docs/documentation/functions/Update-WsaLocalUserPasswordComplexity.md
  docs/documentation/functions/Update-WsaPasswordComplexity.md
  docs/documentation/functions/Update-WsaPasswordExpiration.md
  docs/snippets/wsa-cmdlet-tip.md
Labels: documentation

#80 chore: add `mkdocs-open-in-new-tab`
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, chore

#81 chore: update `RequiredModules`
  VMware.CloudFoundation.PasswordManagement.psd1
Labels: chore

#84 fix: remove errant backticks
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: bug
