Repository vmware/powershell-module-for-vmware-cloud-foundation-password-management, pull requests merged in 2023-05, with the labels that each got.

#28 feat: update `Update-SDDCManagerPasswordComplexity` method
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: enhancement

#29 feat: update `Update-VcenterAccountLockout`
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: feature

#32 fix: drift option for `Request-VcenterAccountLockout`
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: documentation, needs-review

#34 fix: drift option for `Publish-VcenterLocal*` cmdlets
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: documentation

#36 Fix/drift
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: documentation, needs-review

#40 docs: update `README.md` and `CHANGELOG.md`
  CHANGELOG.md
  README.md
Labels: documentation, vcf/5

#41 chore: release updates
  CHANGELOG.md
  README.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: chore
