Repository vmware/powershell-module-for-vmware-cloud-foundation-password-management, pull requests merged in 2024-03, with the labels that each got.

#168 chore: pester tests
  CONTRIBUTING.md
  docs/documentation/testing/index.md
  docs/snippets/import-module-tests.ps1
  docs/user-access.md
  mkdocs.yml
  tests/InputData.json
  tests/PPM.Tests.ps1
  tests/inputData.json.example
Labels: documentation, chore, needs-review, ci

#170 fix: add `VMware.PowerCLI` module to `requiredModules`
  .github/workflows/release.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
Labels: documentation, chore, github-actions, needs-review

#173 chore: add `.vscode` settings
  .vscode/extensions.json
  .vscode/settings.json
Labels: chore

#174 Fixed handling of `Test-VcfPasswordManagementPrereq` while multiple version of module are installed
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: documentation, needs-review

#179 chore(deps): update-dependencies
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  docs/index.md
  docs/snippets/install-module.ps1
  docs/snippets/save-module-local-linux.ps1
  docs/snippets/save-module-local-windows.ps1
Labels: documentation, needs-review

#178 feat: readable `Get-PasswordPolicyDefault` output
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: documentation, needs-review

#182 fix: diff between `inputdata.json` and pester tests
  tests/PPM.Tests.ps1
Labels: documentation, needs-review
