Repository vmware/powershell-module-for-vmware-cloud-foundation-password-management, pull requests merged in 2024-02, with the labels that each got.

#159 chore: support only pwsh 7.2.0 and later
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  docs/index.md
  docs/install.md
Labels: documentation, chore

#160 fix: account lockout policy cmdlets
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
  docs/index.md
  docs/snippets/install-module.ps1
Labels: bug, documentation, needs-review

#164 feat: add 5.1.1.0
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: documentation, enhancement, needs-review
