Repository vmware/powershell-module-for-vmware-cloud-foundation-password-management, pull requests merged in 2024-06, with the labels that each got.

#197 fix: module manifest
  VMware.CloudFoundation.PasswordManagement.psd1
Labels: bug, needs-review

#202 feat: enhance to support photon os 4.0 and 5.0 based appliances
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: documentation, needs-review

#204 feat: add support for vcf-5.2 defaults
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
  docs/index.md
Labels: documentation, enhancement, needs-review
