Repository vmware/powershell-module-for-vmware-cloud-foundation-password-management, pull requests merged in 2024-08, with the labels that each got.

#211 feat: add pester test for aria components
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  tests/PPM.Tests.ps1
Labels: documentation, enhancement, needs-review, ci

#212 fix: update wsa local user password policy
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: bug, needs-review

#215 chore: update user in examples
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
  docs/documentation/functions/Publish-WsaDirectoryPasswordPolicy.md
  docs/documentation/functions/Request-WsaAccountLockout.md
  docs/documentation/functions/Request-WsaPasswordComplexity.md
  docs/documentation/functions/Request-WsaPasswordExpiration.md
  docs/documentation/functions/Update-WsaAccountLockout.md
  docs/documentation/functions/Update-WsaPasswordComplexity.md
  docs/documentation/functions/Update-WsaPasswordExpiration.md
Labels: documentation, chore, needs-review
