Repository vmware/powershell-module-for-vmware-cloud-foundation-password-management, pull requests merged in 2024-01, with the labels that each got.

#149 docs: update for connected and disconnected
  docs/install.md
  mkdocs.yml
Labels: documentation

#150 feat: update for check for password complexity
  CHANGELOG.md
  LICENSE
  Makefile
  NOTICE
  README.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
  mkdocs.yml
Labels: documentation, needs-review

#151 chore: set next release
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  docs/requirements.txt
Labels: documentation, chore, needs-review

#153 chore(deps): bump powervalidatedsolutions from 2.7.0 to 2.8.0
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  docs/index.md
  docs/snippets/install-module.ps1
Labels: documentation, chore, needs-review

#154 chore(deps): bump powervcf from 2.4.0 to 2.4.1
  VMware.CloudFoundation.PasswordManagement.psd1
  docs/index.md
  docs/snippets/install-module.ps1
Labels: documentation, chore, dependencies, needs-review

#157 fix: `Request-VcenterPasswordComplexity` not providing an output
  CHANGELOG.md
  VMware.CloudFoundation.PasswordManagement.psd1
  VMware.CloudFoundation.PasswordManagement.psm1
Labels: bug, documentation, needs-review

#155 chore: release v1.7.1
  CHANGELOG.md
Labels: documentation, chore, needs-review
